version: "3.9"

services:
  api:
    build: ./MovieApi/.
    container_name: api
    ports:
      - "5001:80"
    depends_on:
      - db
    restart: always
    environment:
      - CONNECTION_STRING=Server=db;Database=movies;User Id=developer;Password=secret;
      - S3_USER_ID=abc
      - S3_secret=def
      - S3_bucket_name=bucket_images
  db:
    image: postgres:15.2-alpine
    volumes:
    - ./database:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=secret
